name: Generate a CycloneDX SBOM for Go modules and uploads it to Github.
description: |
  Utilizes cyclonedx-gomod to generate a SBOM. This SBOM will then be archived and uploaded to Github.

inputs:
  publish:
    description: "Publish SBOM to Github"
    required: false
    default: 'false'
  report-retention-days:
    description: Duration in days to preserve reports.
    required: true
    default: "5"
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Action context
      shell: bash
      id: context
      run: |
        working_directory=$(realpath ${{ inputs.working-directory }})
        mkdir -p "$working_directory/build/reports"

        echo "working-directory=$working_directory" >> $GITHUB_OUTPUT
        echo "bom-path=$working_directory/build/reports/bom.json" >> $GITHUB_OUTPUT

    - name: Download cyclonedx-gomod
      uses: CycloneDX/gh-gomod-generate-sbom@v1
      with:
        version: v1
    - name: Generate SBOM
      shell: bash
      working-directory: ${{ steps.context.outputs.working-directory }}
      run: cyclonedx-gomod mod -licenses -json -output ${{ steps.context.outputs.bom-path }}

    - name: Archive BOM
      uses: actions/upload-artifact@v3
      if: "!cancelled()"
      with:
        name: bom.json
        retention-days: ${{ inputs.report-retention-days }}
        path: ${{ steps.context.outputs.bom-path }}

    - name: Upload BOM
      uses: evryfs/sbom-dependency-submission-action@v0.0.14
      with:
        sbom-files: ${{ steps.context.outputs.bom-path }}
